apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: discovery-service
  name: discovery-service
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: discovery-service
      port: 8761
  selector:
    io.kompose.service: discovery-service

