apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: discovery-service-tcp
  name: discovery-service-tcp
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: "8761"
      port: 80
      targetPort: 8761
  selector:
    io.kompose.service: discovery-service
  type: LoadBalancer

