apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: order-service
  name: order-service
  namespace: default
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: order-service

