apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: axon-server
  name: axon-server
  namespace: default
spec:
  ports:
    - name: "8024"
      port: 8024
      targetPort: 8024
    - name: "8124"
      port: 8124
      targetPort: 8124
    - name: "8224"
      port: 8224
      targetPort: 8224
  selector:
    io.kompose.service: axon-server
  type: LoadBalancer


