apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: product-service
  name: product-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/microservice-example-default: "true"
        io.kompose.service: product-service
    spec:
      containers:
        - args:
            - sh
            - -c
            - sleep 2m
          env:
            - name: AXON_AXONSERVER_SERVERS
              value: axon-server:8124
            - name: AXON_EVENTHANDLING_PROCESSORS_PRODUCT-GROUP_MODE
              value: subscribing
            - name: EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE
              value: http://discovery-service:8761/eureka/
            - name: LOGGING_LEVEL_ROOT
              value: info
            - name: LOGGING_PATTERN_CONSOLE
              value: '%d{dd-MM-yyyy HH:mm:ss} [%-5level] [%file:%line] - %msg%n'
            - name: SERVER_ERROR_INCLUDE-BINDING-ERRORS
              value: always
            - name: SERVER_ERROR_INCLUDE-MESSAGE
              value: always
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_APPLICATION_NAME
              value: product-service
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: org.h2.Driver
            - name: SPRING_DATASOURCE_PASSWORD
              value: pass123
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:file:./data/product-service/productsdb;AUTO_SERVER=true
            - name: SPRING_DATASOURCE_USERNAME
              value: user1
            - name: SPRING_H2_CONSOLE_ENABLED
              value: "true"
            - name: SPRING_H2_CONSOLE_SETTINGS_WEB-ALLOW-OTHERS
              value: "true"
            - name: SPRING_JPA_DATABASE-PLATFORM
              value: org.hibernate.dialect.H2Dialect
            - name: SPRING_JPA_HIBERNATE_DDL-AUTO
              value: update
#            - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_ENABLED
#              value: "false"
#            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
#              value: "true"
#            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
#              value: "true"
          image: kirankumarhm/product-service:0.0.1
          imagePullPolicy: Always
#          args: ["--spring.profiles.active=cloud"]
          name: product-service
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data/product-service/productsdb
              name: product-service-hostpath0
      hostname: product-service
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /tmp/data/product-service/productsdb
          name: product-service-hostpath0

